---
name: Release

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js
        type: string
        default: lts/*
      test-command:
        description: Command used to test your TypeScript program
        required: false
        type: string
        default: npm run --if-present test
      prevent-postinstall-scripts:
        description: Flag to prevent post-install scripts
        type: boolean
        default: true
      disable-semantic-release-git:
        description: Disable @semantic-release/git in your release flow. Only takes effect if the action semantic-release config is used.
        type: boolean
        default: false
    secrets:
      npm-token:
        description: API token for writing to your npm registry
        required: true

# Only allow one release workflow to execute at a time, since each release
# workflow uses shared resources (git tags, package registries)
concurrency:
  group: ${{ github.workflow }}

env:
  RUST_BACKTRACE: 1

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Release
        uses: semantic-release-action/typescript/semantic-release@v2
        with:
          node-version: ${{ inputs.node-version }}
          test-command: ${{ inputs.test-command }}
          prevent-postinstall-scripts: ${{ inputs.prevent-postinstall-scripts }}
          disable-semantic-release-git: ${{ inputs.disable-semantic-release-git }}
          npm-token: ${{ secrets.npm-token }}
